version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - docker.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  impulse-test-task:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres

networks:
  postgres:
    driver: bridge